op_name_x_attr_names = [
  ("abs", []),  
  ("accuracy", []),  
  ("accuracy_check", ["fn_name", "res_idx"]),  
  ("acos", []),  
  ("acosh", []),  
  ("adadelta_", ["rho", "epsilon", "multi_precision"]),  
  ("adagrad_", ["epsilon", "multi_precision"]),  
  ("adam_", ["beta1", "beta2", "epsilon", "lazy_mode", "min_row_size_to_use_multithread", "multi_precision", "use_global_beta_pow"]),  
  ("adamax_", ["beta1", "beta2", "epsilon", "multi_precision"]),  
  ("adamw_", ["beta1", "beta2", "epsilon", "lr_ratio", "coeff", "with_decay", "lazy_mode", "min_row_size_to_use_multithread", "multi_precision", "use_global_beta_pow"]),  
  ("addmm", ["beta", "alpha"]),  
  ("affine_grid", ["output_shape", "align_corners"]),  
  ("all", []),  
  ("allclose", ["rtol", "atol", "equal_nan"]),  
  ("amax", []),  
  ("amin", []),  
  ("angle", []),  
  ("any", []),  
  ("apply_per_channel_scale", []),  
  ("argmax", ["axis", "keepdims", "flatten", "dtype"]),  
  ("argmin", ["axis", "keepdims", "flatten", "dtype"]),  
  ("argsort", ["axis", "descending", "stable"]),  
  ("as_complex", []),  
  ("as_real", []),  
  ("as_strided", ["dims", "stride", "offset"]),  
  ("asgd_", ["multi_precision"]),  
  ("asin", []),  
  ("asinh", []),  
  ("assign_out_", []),  
  ("assign_pos", []),  
  ("assign_value_", ["shape", "dtype", "values"]),  
  ("atan", []),  
  ("atan2", []),  
  ("atanh", []),  
  ("auc", ["curve", "num_thresholds", "slide_steps"]),  
  ("average_accumulates_", ["average_window", "max_average_window", "min_average_window"]),  
  ("bce_loss", ["soft_label", "use_softmax", "numeric_stable_mode", "ignore_index", "axis"]),  
  ("bernoulli", []),  
  ("bicubic_interp", ["data_format", "out_d", "out_h", "out_w", "scale", "interp_method", "align_corners", "align_mode"]),  
  ("bilinear", ["bias"]),  
  ("bilinear_interp", ["data_format", "out_d", "out_h", "out_w", "scale", "interp_method", "align_corners", "align_mode"]),  
  ("bincount", ["weights", "minlength"]),  
  ("binomial", []),  
  ("bitwise_and", []),  
  ("bitwise_left_shift", ["is_arithmetic"]),  
  ("bitwise_not", []),  
  ("bitwise_or", []),  
  ("bitwise_right_shift", ["is_arithmetic"]),  
  ("bitwise_xor", []),  
  ("bmm", []),  
  ("box_clip", []),  
  ("box_coder", ["code_type", "box_normalized", "axis", "variance"]),  
  ("broadcast_tensors", []),  
  ("c_allgather", ["ring_id", "nranks", "use_calc_stream"]),  
  ("c_allreduce_max", ["ring_id", "use_calc_stream", "use_model_parallel"]),  
  ("c_allreduce_min", ["ring_id", "use_calc_stream", "use_model_parallel"]),  
  ("c_allreduce_prod", ["ring_id", "use_calc_stream", "use_model_parallel"]),  
  ("c_allreduce_sum", ["ring_id", "use_calc_stream", "use_model_parallel"]),  
  ("c_broadcast", ["ring_id", "root", "use_calc_stream"]),  
  ("c_concat", ["rank", "nranks", "ring_id", "use_calc_stream", "use_model_parallel"]),  
  ("c_identity", ["ring_id", "use_calc_stream", "use_model_parallel"]),  
  ("c_reduce_sum", ["ring_id", "root_id", "use_calc_stream"]),  
  ("c_sync_calc_stream", []),  
  ("c_sync_comm_stream", ["ring_id"]),  
  ("cast", ["dtype"]),  
  ("ceil", []),  
  ("celu", ["alpha"]),  
  ("channel_shuffle", ["groups", "data_format"]),  
  ("check_finite_and_unscale_", []),  
  ("check_numerics", ["op_type", "var_name", "check_nan_inf_level", "stack_height_limit", "output_dir"]),  
  ("cholesky", ["upper"]),  
  ("cholesky_solve", ["upper"]),  
  ("class_center_sample", ["num_classes", "num_samples", "ring_id", "rank", "nranks", "fix_seed", "seed"]),  
  ("clip", ["min", "max"]),  
  ("clip_by_norm", ["max_norm"]),  
  ("coalesce_tensor", ["dtype", "copy_data", "set_constant", "persist_output", "constant", "use_align", "align_size", "size_of_dtype", "concated_shapes", "concated_ranks"]),  
  ("complex", []),  
  ("concat", ["axis"]),  
  ("conj", []),  
  ("conv2d", ["strides", "paddings", "padding_algorithm", "dilations", "groups", "data_format"]),  
  ("conv2d_transpose", ["strides", "paddings", "output_padding", "output_size", "padding_algorithm", "groups", "dilations", "data_format"]),  
  ("conv2d_transpose_bias", ["strides", "paddings", "output_padding", "output_size", "padding_algorithm", "groups", "dilations", "data_format"]),  
  ("conv3d", ["strides", "paddings", "padding_algorithm", "groups", "dilations", "data_format"]),  
  ("conv3d_transpose", ["strides", "paddings", "output_padding", "output_size", "padding_algorithm", "groups", "dilations", "data_format"]),  
  ("copy_to", ["place", "blocking"]),  
  ("copysign", []),  
  ("correlation", ["pad_size", "kernel_size", "max_displacement", "stride1", "stride2", "corr_type_multiply"]),  
  ("cos", []),  
  ("cosh", []),  
  ("crf_decoding", ["label", "length"]),  
  ("crop", ["shape", "offsets"]),  
  ("cross", ["axis"]),  
  ("cross_entropy_with_softmax", ["soft_label", "use_softmax", "numeric_stable_mode", "ignore_index", "axis"]),  
  ("ctc_align", ["blank", "merge_repeated", "padding_value"]),  
  ("cudnn_lstm", ["init_h", "init_c", "w", "weight_list", "sequence_length", "dropout_prob", "is_bidirec", "hidden_size", "num_layers", "is_test", "seed"]),  
  ("cummax", ["axis", "dtype"]),  
  ("cummin", ["axis", "dtype"]),  
  ("cumprod", ["dim", "exclusive", "reverse"]),  
  ("cumsum", ["axis", "flatten", "exclusive", "reverse"]),  
  ("data", ["name", "shape", "dtype", "place"]),  
  ("decayed_adagrad", ["decay", "epsilon"]),  
  ("decode_jpeg", ["mode", "place"]),  
  ("deformable_conv", ["strides", "paddings", "dilations", "deformable_groups", "groups", "im2col_step"]),  
  ("depend", []),  
  ("depthwise_conv2d", ["strides", "paddings", "padding_algorithm", "groups", "dilations", "data_format"]),  
  ("depthwise_conv2d_transpose", ["strides", "paddings", "output_padding", "output_size", "padding_algorithm", "groups", "dilations", "data_format"]),  
  ("dequantize_abs_max", ["max_range"]),  
  ("dequantize_log", []),  
  ("det", []),  
  ("detection_map", ["class_num", "background_label", "overlap_threshold", "evaluate_difficult", "ap_type"]),  
  ("dgc", ["m", "use_nesterov", "sparsity", "rampup_begin_step", "rampup_step", "regular_coeff", "regular_type"]),  
  ("dgc_momentum", ["mu", "use_nesterov", "regularization_method", "regularization_coeff", "multi_precision", "rescale_grad", "rampup_begin_step"]),  
  ("diag", ["offset", "padding_value"]),  
  ("diag_embed", ["offset", "dim1", "dim2"]),  
  ("diagonal", ["offset", "axis1", "axis2"]),  
  ("digamma", []),  
  ("dirichlet", []),
  ("disable_check_model_nan_inf", ["flag"]),  
  ("dist", ["p"]),  
  ("dot", []),  
  ("dropout", ["p", "is_test", "mode", "seed", "fix_seed"]),  
  ("edit_distance", ["normalized", "hypslength", "refslength"]),  
  ("eig", []),  
  ("eigh", ["UPLO"]),  
  ("eigvals", []),  
  ("eigvalsh", ["uplo", "is_test"]),  
  ("elu", ["alpha"]),  
  ("empty", ["shape", "dtype", "place"]),  
  ("empty_like", ["dtype", "place"]),  
  ("enable_check_model_nan_inf", ["flag"]),  
  ("equal_all", []),  
  ("erf", []),  
  ("erfinv", []),  
  ("exp", []),  
  ("expand", ["shape"]),  
  ("expand_as", ["target_shape"]),  
  ("expm1", []),  
  ("exponential_", ["lam"]),  
  ("eye", ["num_rows", "num_columns", "dtype", "place"]),  
  ("fake_channel_wise_dequantize_max_abs", ["quant_bits", "quant_axis", "x_num_col_dims"]),  
  ("fake_channel_wise_quantize_abs_max", ["bit_length", "round_type", "quant_axis", "is_test"]),  
  ("fake_channel_wise_quantize_dequantize_abs_max", ["bit_length", "round_type", "quant_axis"]),  
  ("fake_dequantize_max_abs", ["max_range"]),  
  ("fake_quantize_abs_max", ["bit_length", "round_type"]),  
  ("fake_quantize_dequantize_abs_max", ["bit_length", "round_type"]),  
  ("fake_quantize_dequantize_moving_average_abs_max", ["moving_rate", "bit_length", "is_test", "round_type"]),  
  ("fake_quantize_moving_average_abs_max", ["moving_rate", "bit_length", "is_test", "round_type"]),  
  ("fake_quantize_range_abs_max", ["in_scale", "iter", "window_size", "bit_length", "is_test", "round_type"]),  
  ("fft_c2c", ["axes", "normalization", "forward"]),  
  ("fft_c2r", ["axes", "normalization", "forward", "last_dim_size"]),  
  ("fft_r2c", ["axes", "normalization", "forward", "onesided"]),  
  ("fill", ["value"]),  
  ("fill_diagonal", ["value", "offset", "wrap"]),  
  ("fill_diagonal_tensor", ["offset", "dim1", "dim2"]),  
  ("flash_attn", ["fixed_seed_offset", "attn_mask", "dropout", "causal", "return_softmax", "is_test", "rng_name"]),  
  ("flash_attn_qkvpacked", ["fixed_seed_offset", "attn_mask", "dropout", "causal", "return_softmax", "is_test", "rng_name"]),  
  ("flash_attn_unpadded", ["fixed_seed_offset", "attn_mask", "max_seqlen_q", "max_seqlen_k", "scale", "dropout", "causal", "return_softmax", "is_test", "rng_name"]),  
  ("flash_attn_varlen_qkvpacked", ["fixed_seed_offset", "attn_mask", "max_seqlen_q", "max_seqlen_k", "scale", "dropout", "causal", "return_softmax", "is_test", "rng_name", "varlen_padded"]),  
  ("flash_attn_with_sparse_mask", ["fixed_seed_offset", "attn_mask", "attn_mask_start_row", "dropout", "causal", "return_softmax", "is_test", "rng_name"]),  
  ("flatten", ["start_axis", "stop_axis"]),  
  ("flip", ["axis"]),  
  ("floor", []),  
  ("fmax", []),  
  ("fmin", []),  
  ("fold", ["output_sizes", "kernel_sizes", "strides", "paddings", "dilations"]),  
  ("fractional_max_pool2d", ["output_size", "kernel_size", "random_u", "return_mask"]),  
  ("fractional_max_pool3d", ["output_size", "kernel_size", "random_u", "return_mask"]),  
  ("frame", ["frame_length", "hop_length", "axis"]),  
  ("frobenius_norm", ["axis", "keep_dim", "reduce_all"]),  
  ("full", ["shape", "value", "dtype", "place"]),  
  ("full_", ["shape", "value", "dtype", "place"]),  
  ("full_batch_size_like", ["shape", "value", "dtype", "input_dim_idx", "output_dim_idx", "place"]),  
  ("full_int_array", ["value", "dtype", "place"]),  
  ("full_like", ["value", "dtype", "place"]),  
  ("full_with_tensor", ["dtype"]),  
  ("fused_batch_norm_act", ["momentum", "epsilon", "act_type"]),  
  ("fused_bn_add_activation", ["momentum", "epsilon", "act_type"]),  
  ("fused_multi_transformer", ["pre_layer_norm", "epsilon", "residual_alpha", "dropout_rate", "rotary_emb_dims", "is_test", "dropout_implementation", "act_method", "trans_qkvw", "ring_id", "norm_type", "use_neox_rotary_style", "gqa_group_size"]),  
  ("fused_softmax_mask", []),  
  ("fused_softmax_mask_upper_triangle", []),  
  ("gammaincc", []),  
  ("gammaln", []),  
  ("gather", ["axis"]),  
  ("gather_nd", []),  
  ("gather_tree", []),  
  ("gaussian", ["mean", "std", "seed", "dtype", "place"]),  
  ("gaussian_inplace", ["mean", "std", "seed"]),  
  ("gelu", ["approximate"]),  
  ("generate_proposals", ["pre_nms_top_n", "post_nms_top_n", "nms_thresh", "min_size", "eta", "pixel_offset"]),  
  ("graph_khop_sampler", ["sample_sizes", "return_eids"]),  
  ("graph_sample_neighbors", ["sample_size", "return_eids", "flag_perm_buffer"]),  
  ("grid_sample", ["mode", "padding_mode", "align_corners"]),  
  ("group_norm", ["epsilon", "groups", "data_format"]),  
  ("gru", ["activation", "gate_activation", "is_reverse", "origin_mode", "is_test"]),  
  ("gru_unit", ["activation", "gate_activation", "origin_mode"]),  
  ("gumbel_softmax", ["temperature", "hard", "axis"]),  
  ("hardshrink", ["threshold"]),  
  ("hardsigmoid", ["slope", "offset"]),  
  ("hardtanh", ["t_min", "t_max"]),  
  ("heaviside", []),  
  ("histogram", ["bins", "min", "max"]),  
  ("hsigmoid_loss", ["w", "bias", "path", "code", "num_classes", "is_sparse"]),  
  ("huber_loss", ["delta"]),  
  ("i0", []),  
  ("i0e", []),  
  ("i1", []),  
  ("i1e", []),  
  ("identity_loss", ["reduction"]),  
  ("imag", []),  
  ("increment", ["value"]),  
  ("index_add", ["axis"]),  
  ("index_put", ["accumulate"]),  
  ("index_sample", []),  
  ("index_select", ["axis"]),  
  ("index_select_strided", ["index", "axis"]),  
  ("instance_norm", []),  
  ("inverse", []),  
  ("is_empty", []),  
  ("isclose", ["rtol", "atol", "equal_nan"]),  
  ("isfinite", []),  
  ("isinf", []),  
  ("isnan", []),  
  ("kldiv_loss", ["reduction", "log_target"]),  
  ("kron", []),  
  ("kthvalue", ["k", "axis", "keepdim"]),  
  ("l1_norm", []),  
  ("label_smooth", ["prior_dist", "epsilon"]),  
  ("lamb_", ["beta1", "beta2", "epsilon", "always_adapt", "multi_precision"]),  
  ("layer_norm", ["epsilon", "begin_norm_axis"]),  
  ("leaky_relu", ["negative_slope"]),  
  ("lerp", []),  
  ("lgamma", []),  
  ("limit_by_capacity", ["n_worker"]),  
  ("linear_interp", ["data_format", "out_d", "out_h", "out_w", "scale", "interp_method", "align_corners", "align_mode"]),  
  ("linspace", ["number", "dtype", "place"]),  
  ("llm_int8_linear", ["threshold"]),  
  ("log", []),  
  ("log10", []),  
  ("log1p", []),  
  ("log2", []),
  ("log_loss", ["epsilon"]),  
  ("log_softmax", ["axis"]),  
  ("logcumsumexp", ["axis", "flatten", "exclusive", "reverse"]),  
  ("logical_and", []),  
  ("logical_not", []),  
  ("logical_or", []),  
  ("logical_xor", []),  
  ("logit", ["eps"]),  
  ("logsigmoid", []),  
  ("logspace", ["num", "base", "dtype", "place"]),  
  ("logsumexp", ["axis", "keepdim", "reduce_all"]),  
  ("lstsq", ["rcond", "driver"]),  
  ("lu", ["pivot"]),  
  ("lu_unpack", ["unpack_ludata", "unpack_pivots"]),  
  ("margin_cross_entropy", ["return_softmax", "ring_id", "rank", "nranks", "margin1", "margin2", "margin3", "scale"]),  
  ("masked_multihead_attention_", ["bias", "src_mask", "cum_offsets", "sequence_lengths", "rotary_tensor", "beam_cache_offset", "qkv_out_scale", "out_shift", "out_smooth", "seq_len", "rotary_emb_dims", "use_neox_rotary_style", "compute_dtype", "out_scale", "quant_round_type", "quant_max_bound", "quant_min_bound"]),  
  ("masked_select", []),  
  ("matrix_nms", ["score_threshold", "nms_top_k", "keep_top_k", "post_threshold", "use_gaussian", "gaussian_sigma", "background_label", "normalized"]),  
  ("matrix_power", ["n"]),  
  ("matrix_rank", ["tol", "use_default_tol", "hermitian"]),  
  ("matrix_rank_tol", ["atol_tensor", "use_default_tol", "hermitian"]),  
  ("max", []),  
  ("max_pool2d_with_index", ["strides", "paddings", "ceil_mode", "exclusive", "data_format", "pooling_type", "global_pooling", "adaptive", "padding_algorithm"]),  
  ("max_pool3d_with_index", ["strides", "paddings", "ceil_mode", "exclusive", "data_format", "pooling_type", "global_pooling", "adaptive", "padding_algorithm"]),  
  ("maxout", ["groups", "axis"]),  
  ("mean", []),  
  ("mean_all", []),  
  ("memcpy_d2h", ["dst_place_type"]),  
  ("memcpy_h2d", ["dst_place_type"]),  
  ("memory_efficient_attention", ["cu_seqlens_q", "cu_seqlens_k", "causal_diagonal", "seqlen_k", "max_seqlen_q", "max_seqlen_k", "causal", "dropout_p", "scale", "is_test"]),  
  ("merge_selected_rows", []),  
  ("merged_adam_", ["beta1", "beta2", "epsilon", "multi_precision", "use_global_beta_pow"]),  
  ("merged_momentum_", ["mu", "use_nesterov", "regularization_method", "regularization_coeff", "multi_precision", "rescale_grad"]),  
  ("meshgrid", []),  
  ("mish", ["lambda"]),  
  ("mode", ["axis", "keepdim"]),  
  ("momentum_", ["mu", "use_nesterov", "regularization_method", "regularization_coeff", "multi_precision", "rescale_grad"]),  
  ("multi_dot", []),  
  ("multiclass_nms3", ["score_threshold", "nms_top_k", "keep_top_k", "nms_threshold", "normalized", "nms_eta", "background_label"]),  
  ("multinomial", ["num_samples", "replacement"]),  
  ("multiplex", []),  
  ("mv", []),  
  ("nadam_", ["beta1", "beta2", "epsilon", "momentum_decay", "multi_precision"]),  
  ("nanmedian", ["axis", "keepdim", "mode"]),  
  ("nearest_interp", ["data_format", "out_d", "out_h", "out_w", "scale", "interp_method", "align_corners", "align_mode"]),  
  ("nextafter", []),  
  ("nll_loss", ["weight", "ignore_index", "reduction"]),  
  ("nms", ["threshold"]),  
  ("nonzero", []),  
  ("norm", ["axis", "epsilon", "is_test"]),  
  ("npu_identity", ["format"]),  
  ("numel", []),  
  ("one_hot", ["num_classes"]),  
  ("ones", ["shape", "dtype", "place"]),  
  ("ones_like", ["dtype", "place"]),  
  ("overlap_add", ["hop_length", "axis"]),  
  ("p_norm", ["porder", "axis", "epsilon", "keepdim", "asvector"]),  
  ("pad", ["paddings", "pad_value"]),  
  ("pad3d", ["mode", "pad_value", "data_format"]),  
  ("partial_concat", ["start_index", "length"]),  
  ("partial_sum", ["start_index", "length"]),  
  ("pixel_shuffle", ["upscale_factor", "data_format"]),  
  ("pixel_unshuffle", ["downscale_factor", "data_format"]),  
  ("poisson", []),  
  ("polygamma", ["n"]),  
  ("pool2d", ["strides", "paddings", "ceil_mode", "exclusive", "data_format", "pooling_type", "global_pooling", "adaptive", "padding_algorithm"]),  
  ("pool3d", ["strides", "paddings", "ceil_mode", "exclusive", "data_format", "pooling_type", "global_pooling", "adaptive", "padding_algorithm"]),  
  ("pow", ["y"]),  
  ("prelu", ["alpha", "data_format", "mode"]),  
  ("prior_box", ["min_sizes", "max_sizes", "aspect_ratios", "variances", "flip", "clip", "step_w", "step_h", "offset", "min_max_aspect_ratios_order"]),  
  ("prod", ["dims", "keep_dim", "reduce_all"]),  
  ("psroi_pool", ["pooled_height", "pooled_width", "output_channels", "spatial_scale"]),  
  ("put_along_axis", ["axis", "reduce", "include_self"]),  
  ("pyramid_hash", ["num_emb", "space_len", "pyramid_layer", "rand_len", "drop_out_percent", "is_training", "use_filter", "white_list_len", "black_list_len", "seed", "lr", "distribute_update_vars"]),  
  ("qr", ["mode"]),  
  ("radam_", ["beta1", "beta2", "epsilon", "multi_precision"]),  
  ("randint", ["low", "high", "shape", "dtype", "place"]),  
  ("random_routing", []),  
  ("randperm", ["n", "dtype", "place"]),  
  ("rank_attention", ["max_rank", "max_size"]),  
  ("read_file", ["filename", "dtype", "place"]),  
  ("real", []),  
  ("reciprocal", []),  
  ("reduce_as", []),  
  ("reindex_graph", ["hashtable_value", "hashtable_index"]),  
  ("relu", []),  
  ("relu6", []),  
  ("renorm", ["p", "axis", "max_norm"]),  
  ("repeat_interleave", ["repeats", "axis"]),  
  ("reverse", ["axis"]),  
  ("rms_norm", ["bias", "residual", "norm_weight", "norm_bias", "epsilon", "begin_norm_axis", "quant_scale", "quant_round_type", "quant_max_bound", "quant_min_bound"]),  
  ("rmsprop_", ["epsilon", "decay", "momentum", "centered", "multi_precision"]),  
  ("rnn", ["pre_state", "weight_list", "sequence_length", "dropout_state_in", "dropout_prob", "is_bidirec", "input_size", "hidden_size", "num_layers", "mode", "seed", "is_test"]),  
  ("roi_align", ["boxes", "boxes_num", "pooled_height", "pooled_width", "spatial_scale", "sampling_ratio", "aligned"]),  
  ("roi_pool", ["boxes", "boxes_num", "pooled_height", "pooled_width", "spatial_scale"]),  
  ("roll", ["shifts", "axis"]),  
  ("round", []),  
  ("rprop_", ["learning_rate_range", "etas", "multi_precision"]),  
  ("rrelu", ["lower", "upper", "is_test"]),  
  ("rsqrt", []),  
  ("scale", ["scale", "bias", "bias_after_scale"]),  
  ("scatter", ["overwrite"]),  
  ("scatter_nd_add", []),  
  ("searchsorted", ["out_int32", "right"]),  
  ("segment_pool", ["pooltype"]),  
  ("selu", ["scale", "alpha"]),  
  ("send_u_recv", ["reduce_op", "out_size"]),
  ("send_ue_recv", ["y", "src_index", "dst_index", "message_op", "reduce_op", "out_size"]),  
  ("send_uv", ["y", "src_index", "dst_index", "message_op"]),  
  ("sequence_conv", ["padding_data", "context_length", "padding_trainable", "context_start", "context_stride"]),  
  ("sequence_mask", ["max_len", "out_dtype"]),  
  ("set_value_with_tensor", ["starts", "ends", "steps", "axes", "decrease_axes", "none_axes"]),  
  ("sgd_", ["multi_precision"]),  
  ("shape", []),  
  ("shard_index", ["index_num", "nshards", "shard_id", "ignore_value"]),  
  ("shuffle_channel", ["group"]),  
  ("sigmoid", []),  
  ("sigmoid_cross_entropy_with_logits", ["pos_weight", "normalize", "ignore_index"]),  
  ("sign", []),  
  ("silu", []),  
  ("sin", []),  
  ("sinh", []),  
  ("slice", ["axes", "starts", "ends", "infer_flags", "decrease_axis"]),  
  ("slogdet", []),  
  ("softplus", ["beta", "threshold"]),  
  ("softshrink", ["threshold"]),  
  ("softsign", []),  
  ("solve", []),  
  ("sparse_attention", ["offset", "columns", "key_padding_mask", "attn_mask"]),  
  ("spectral_norm", ["dim", "power_iters", "eps"]),  
  ("split", ["sections", "axis"]),  
  ("split_with_num", ["num", "axis"]),  
  ("sqrt", []),  
  ("square", []),  
  ("squared_l2_norm", []),  
  ("squeeze", ["axis"]),  
  ("stack", ["axis"]),  
  ("standard_gamma", []),  
  ("stanh", ["scale_a", "scale_b"]),  
  ("stft", ["window", "n_fft", "hop_length", "normalized", "onesided"]),  
  ("strided_slice", ["axes", "starts", "ends", "strides"]),  
  ("sum", ["axis", "dtype", "keepdim"]),  
  ("svd", ["full_matrices"]),  
  ("swiglu", []),  
  ("swish", []),  
  ("sync_batch_norm_", ["is_test", "momentum", "epsilon", "data_format", "use_global_stats", "trainable_statistics"]),  
  ("take_along_axis", ["indices", "axis"]),  
  ("tan", []),  
  ("tanh", []),  
  ("tanh_shrink", []),  
  ("tdm_child", ["child_nums", "dtype"]),  
  ("tdm_sampler", ["output_positive", "neg_samples_num_list", "layer_offset_lod", "seed", "dtype"]),  
  ("temporal_shift", ["seg_num", "shift_ratio", "data_format"]),  
  ("tensor_unfold", ["axis", "size", "step"]),  
  ("thresholded_relu", ["threshold"]),  
  ("top_p_sampling", ["ps", "threshold", "seed"]),  
  ("topk", ["k", "axis", "largest", "sorted"]),  
  ("trace", ["offset", "axis1", "axis2"]),  
  ("trans_layout", ["perm"]),  
  ("transpose", ["perm"]),  
  ("triangular_solve", ["upper", "transpose", "unitriangular"]),  
  ("tril", ["diagonal"]),  
  ("tril_indices", ["rows", "cols", "offset", "dtype", "place"]),  
  ("trilinear_interp", ["data_format", "out_d", "out_h", "out_w", "scale", "interp_method", "align_corners", "align_mode"]),  
  ("triu", ["diagonal"]),  
  ("triu_indices", ["row", "col", "offset", "dtype", "place"]),  
  ("trunc", []),  
  ("truncated_gaussian_random", ["shape", "mean", "std", "seed", "a", "b", "dtype", "place"]),  
  ("unbind", ["axis"]),  
  ("unfold", ["kernel_sizes", "strides", "paddings", "dilations"]),  
  ("uniform", ["shape", "dtype", "min", "max", "seed", "place"]),  
  ("uniform_inplace", ["min", "max", "seed", "diag_num", "diag_step", "diag_val"]),  
  ("uniform_random_batch_size_like", ["input", "input_dim_idx", "output_dim_idx", "min", "max", "seed", "diag_num", "diag_step", "diag_val", "dtype"]),  
  ("unique_consecutive", ["return_inverse", "return_counts", "axis", "dtype"]),  
  ("unpool", ["indices", "ksize", "strides", "padding", "output_size", "data_format"]),  
  ("unpool3d", ["indices", "ksize", "strides", "paddings", "output_size", "data_format"]),  
  ("unsqueeze", ["axis"]),  
  ("unstack", ["axis", "num"]),  
  ("update_loss_scaling_", ["incr_every_n_steps", "decr_every_n_nan_or_inf", "incr_ratio", "decr_ratio", "stop_update"]),  
  ("view_dtype", ["dtype"]),  
  ("view_shape", ["dims"]),  
  ("viterbi_decode", ["include_bos_eos_tag"]),  
  ("warpctc", ["blank", "norm_by_times"]),  
  ("warprnnt", ["blank", "fastemit_lambda"]),  
  ("weight_dequantize", ["algo", "out_dtype", "group_size"]),  
  ("weight_only_linear", ["bias", "weight_dtype", "arch", "group_size"]),  
  ("weight_quantize", ["algo", "arch", "group_size"]),  
  ("weighted_sample_neighbors", ["edge_weight", "input_nodes", "eids"]),  
  ("where", []),  
  ("yolo_box", ["img_size", "anchors", "class_num", "conf_thresh", "downsample_ratio", "clip_bbox", "scale_x_y", "iou_aware", "iou_aware_factor"]),  
  ("yolo_box_head", ["anchors", "class_num"]),  
  ("yolo_box_post", ["anchors0", "anchors1", "anchors2", "class_num", "conf_thresh", "downsample_ratio0", "downsample_ratio1", "downsample_ratio2", "clip_bbox", "scale_x_y", "nms_threshold"]),  
  ("yolo_loss", ["gt_box", "gt_label", "gt_score", "anchors", "anchor_mask", "class_num", "ignore_thresh", "downsample_ratio", "use_label_smooth", "scale_x_y"]),  
  ("zeros", ["shape", "dtype", "place"]),  
  ("zeros_like", ["dtype", "place"]),  
  ("chunk_eval", ["num_chunk_types", "chunk_scheme", "excluded_chunk_types"]),  
  ("moe", ["gate", "bmm0", "bias0", "bmm1", "bias1", "act_type"]),  
  ("number_count", ["upper_range"]),
]