phi_ops_yaml_ops = [
("abs", "x"),  
("accuracy", "x", "indices", "label"),  
("accuracy_check", "x", "y", "fn_name", "res_idx"),  
("acos", "x"),  
("acosh", "x"),  
("adadelta_", "param", "grad", "avg_squared_grad", "avg_squared_update", "learning_rate", "master_param", "rho", "epsilon", "multi_precision"),  
("adagrad_", "param", "grad", "moment", "learning_rate", "master_param", "epsilon", "multi_precision"),  
("adam_", "param", "grad", "learning_rate", "moment1", "moment2", "beta1_pow", "beta2_pow", "master_param", "skip_update", "beta1", "beta2", "epsilon", "lazy_mode", "min_row_size_to_use_multithread", "multi_precision", "use_global_beta_pow"),  
("adamax_", "param", "grad", "learning_rate", "moment", "inf_norm", "beta1_pow", "master_param", "beta1", "beta2", "epsilon", "multi_precision"),  
("adamw_", "param", "grad", "learning_rate", "moment1", "moment2", "beta1_pow", "beta2_pow", "master_param", "skip_update", "beta1", "beta2", "epsilon", "lr_ratio", "coeff", "with_decay", "lazy_mode", "min_row_size_to_use_multithread", "multi_precision", "use_global_beta_pow"),  
("addmm", "input", "x", "y", "beta", "alpha"),  
("affine_grid", "input", "output_shape", "align_corners"),  
("all", "x", "axis", "keepdim"),  
("allclose", "x", "y", "rtol", "atol", "equal_nan"),  
("amax", "x", "axis", "keepdim"),  
("amin", "x", "axis", "keepdim"),  
("angle", "x"),  
("any", "x", "axis", "keepdim"),  
("apply_per_channel_scale", "x", "scales"),  
("argmax", "x", "axis", "keepdims", "flatten", "dtype"),  
("argmin", "x", "axis", "keepdims", "flatten", "dtype"),  
("argsort", "x", "axis", "descending", "stable"),  
("as_complex", "x"),  
("as_real", "x"),  
("as_strided", "input", "dims", "stride", "offset"),  
("asgd_", "param", "grad", "learning_rate", "d", "y", "n", "master_param", "multi_precision"),  
("asin", "x"),  
("asinh", "x"),  
("assign_out_", "x", "output"),  
("assign_pos", "x", "cum_count", "eff_num_len"),  
("assign_value_", "output", "shape", "dtype", "values", "place"),  
("atan", "x"),  
("atan2", "x", "y"),  
("atanh", "x"),  
("auc", "x", "label", "stat_pos", "stat_neg", "ins_tag_weight", "curve", "num_thresholds", "slide_steps"),  
("average_accumulates_", "param", "in_sum_1", "in_sum_2", "in_sum_3", "in_num_accumulates", "in_old_num_accumulates", "in_num_updates", "average_window", "max_average_window", "min_average_window"),  
("bce_loss", "input", "label", "soft_label", "use_softmax", "numeric_stable_mode", "ignore_index", "axis"),  
("bernoulli", "x"),  
("bicubic_interp", "x", "out_size", "size_tensor", "scale_tensor", "data_format", "out_d", "out_h", "out_w", "scale", "interp_method", "align_corners", "align_mode"),  
("bilinear", "x", "y", "weight", "bias"),  
("bilinear_interp", "x", "out_size", "size_tensor", "scale_tensor", "data_format", "out_d", "out_h", "out_w", "scale", "interp_method", "align_corners", "align_mode"),  
("abs", "x"),  
("accuracy", "x", "indices", "label"),  
("accuracy_check", "x", "y", "fn_name", "res_idx"),  
("acos", "x"),  
("acosh", "x"),  
("adadelta_", "param", "grad", "avg_squared_grad", "avg_squared_update", "learning_rate", "master_param", "rho", "epsilon", "multi_precision"),  
("adagrad_", "param", "grad", "moment", "learning_rate", "master_param", "epsilon", "multi_precision"),  
("adam_", "param", "grad", "learning_rate", "moment1", "moment2", "beta1_pow", "beta2_pow", "master_param", "skip_update", "beta1", "beta2", "epsilon", "lazy_mode", "min_row_size_to_use_multithread", "multi_precision", "use_global_beta_pow"),  
("adamax_", "param", "grad", "learning_rate", "moment", "inf_norm", "beta1_pow", "master_param", "beta1", "beta2", "epsilon", "multi_precision"),  
("adamw_", "param", "grad", "learning_rate", "moment1", "moment2", "beta1_pow", "beta2_pow", "master_param", "skip_update", "beta1", "beta2", "epsilon", "lr_ratio", "coeff", "with_decay", "lazy_mode", "min_row_size_to_use_multithread", "multi_precision", "use_global_beta_pow"),  
("addmm", "input", "x", "y", "beta", "alpha"),  
("affine_grid", "input", "output_shape", "align_corners"),  
("all", "x", "axis", "keepdim"),  
("allclose", "x", "y", "rtol", "atol", "equal_nan"),  
("amax", "x", "axis", "keepdim"),  
("amin", "x", "axis", "keepdim"),  
("angle", "x"),  
("any", "x", "axis", "keepdim"),  
("apply_per_channel_scale", "x", "scales"),  
("argmax", "x", "axis", "keepdims", "flatten", "dtype"),  
("argmin", "x", "axis", "keepdims", "flatten", "dtype"),  
("argsort", "x", "axis", "descending", "stable"),  
("as_complex", "x"),  
("as_real", "x"),  
("as_strided", "input", "dims", "stride", "offset"),  
("asgd_", "param", "grad", "learning_rate", "d", "y", "n", "master_param", "multi_precision"),  
("asin", "x"),  
("asinh", "x"),  
("assign_out_", "x", "output"),  
("assign_pos", "x", "cum_count", "eff_num_len"),  
("assign_value_", "output", "shape", "dtype", "values", "place"),  
("atan", "x"),  
("atan2", "x", "y"),  
("atanh", "x"),  
("auc", "x", "label", "stat_pos", "stat_neg", "ins_tag_weight", "curve", "num_thresholds", "slide_steps"),  
("average_accumulates_", "param", "in_sum_1", "in_sum_2", "in_sum_3", "in_num_accumulates", "in_old_num_accumulates", "in_num_updates", "average_window", "max_average_window", "min_average_window"),  
("bce_loss", "input", "label"),  
("bernoulli", "x"),  
("bicubic_interp", "x", "out_size", "size_tensor", "scale_tensor", "data_format", "out_d", "out_h", "out_w", "scale", "interp_method", "align_corners", "align_mode"),  
("bilinear", "x", "y", "weight", "bias"),  
("bilinear_interp", "x", "out_size", "size_tensor", "scale_tensor", "data_format", "out_d", "out_h", "out_w", "scale", "interp_method", "align_corners", "align_mode"),  
("bincount", "x", "weights", "minlength"),  
("binomial", "count", "prob"),  
("bitwise_and", "x", "y"),  
("bitwise_left_shift", "x", "y", "is_arithmetic"),  
("bitwise_not", "x"),  
("bitwise_or", "x", "y"),  
("bitwise_right_shift", "x", "y", "is_arithmetic"),  
("bitwise_xor", "x", "y"),  
("bmm", "x", "y"),  
("box_clip", "input", "im_info"),  
("box_coder", "prior_box", "prior_box_var", "target_box", "code_type", "box_normalized", "axis", "variance"),  
("broadcast_tensors", "input"),  
("c_allgather", "x", "ring_id", "nranks", "use_calc_stream"),  
("c_allreduce_max", "x", "ring_id", "use_calc_stream", "use_model_parallel"),  
("c_allreduce_min", "x", "ring_id", "use_calc_stream", "use_model_parallel"),  
("c_allreduce_prod", "x", "ring_id", "use_calc_stream", "use_model_parallel"),  
("c_allreduce_sum", "x", "ring_id", "use_calc_stream", "use_model_parallel"),  
("c_broadcast", "x", "ring_id", "root", "use_calc_stream"),  
("c_concat", "x", "rank", "nranks", "ring_id", "use_calc_stream", "use_model_parallel"),  
("c_identity", "x", "ring_id", "use_calc_stream", "use_model_parallel"),  
("c_reduce_sum", "x", "ring_id", "root_id", "use_calc_stream"),  
("c_sync_calc_stream", "x"),  
("c_sync_comm_stream", "x", "ring_id"),  
("cast", "x", "dtype"),  
("ceil", "x"),  
("celu", "x", "alpha"),  
("channel_shuffle", "x", "groups", "data_format"),  
("check_finite_and_unscale_", "x", "scale"),  
("check_numerics", "tensor", "op_type", "var_name", "check_nan_inf_level", "stack_height_limit", "output_dir"),  
("cholesky", "x", "upper"),  
("cholesky_solve", "x", "y", "upper"),  
("class_center_sample", "label", "num_classes", "num_samples", "ring_id", "rank", "nranks", "fix_seed", "seed"),  
("clip", "x", "min", "max"),  
("clip_by_norm", "x", "max_norm"),  
("coalesce_tensor", "input", "dtype", "copy_data", "set_constant", "persist_output", "constant", "use_align", "align_size", "size_of_dtype", "concated_shapes", "concated_ranks"),  
("complex", "real", "imag"),  
("concat", "x", "axis"),  
("conj", "x"),  
("conv2d", "input", "filter", "strides", "paddings", "padding_algorithm", "dilations", "groups", "data_format"),  
("conv2d_transpose", "x", "filter", "strides", "paddings", "output_padding", "output_size", "padding_algorithm", "groups", "dilations", "data_format"),  
("conv2d_transpose_bias", "x", "filter", "bias", "strides", "paddings", "output_padding", "output_size", "padding_algorithm", "groups", "dilations", "data_format"),  
("conv3d", "input", "filter", "strides", "paddings", "padding_algorithm", "groups", "dilations", "data_format"),  
("conv3d_transpose", "x", "filter", "strides", "paddings", "output_padding", "output_size", "padding_algorithm", "groups", "dilations", "data_format"),  
("copy_to", "x", "place", "blocking"),  
("copysign", "x", "y"),  
("correlation", "input1", "input2", "pad_size", "kernel_size", "max_displacement", "stride1", "stride2", "corr_type_multiply"),  
("cos", "x"),  
("cosh", "x"),  
("crf_decoding", "emission", "transition", "label", "length"),  
("crop", "x", "shape", "offsets"),  
("cross", "x", "y", "axis"),  
("cross_entropy_with_softmax", "input", "label", "soft_label", "use_softmax", "numeric_stable_mode", "ignore_index", "axis"),  
("ctc_align", "input", "input_length", "blank", "merge_repeated", "padding_value"),  
("cudnn_lstm", "x", "init_h", "init_c", "w", "weight_list", "sequence_length", "dropout_prob", "is_bidirec", "hidden_size", "num_layers", "is_test", "seed"),  
("cummax", "x", "axis", "dtype"),  
("cummin", "x", "axis", "dtype"),  
("cumprod", "x", "dim", "exclusive", "reverse"),  
("cumsum", "x", "axis", "flatten", "exclusive", "reverse"),  
("data", "name", "shape", "dtype", "place"),  
("decayed_adagrad", "param", "grad", "moment", "learning_rate", "decay", "epsilon"),  
("decode_jpeg", "x", "mode", "place"),  
("deformable_conv", "x", "offset", "filter", "mask", "strides", "paddings", "dilations", "deformable_groups", "groups", "im2col_step"),  
("depend", "x", "dep"),  
("depthwise_conv2d", "input", "filter", "strides", "paddings", "padding_algorithm", "groups", "dilations", "data_format"),  
("depthwise_conv2d_transpose", "x", "filter", "strides", "paddings", "output_padding", "output_size", "padding_algorithm", "groups", "dilations", "data_format"),  
("dequantize_abs_max", "x", "scale", "max_range"),  
("dequantize_log", "x", "dict"),  
("det", "x"),  
("detection_map", "detect_res", "label", "has_state", "pos_count", "true_pos", "false_pos", "class_num", "background_label", "overlap_threshold", "evaluate_difficult", "ap_type"),  
("dgc", "u", "v", "grad", "param", "current_step", "nranks", "m", "use_nesterov", "sparsity", "rampup_begin_step", "rampup_step", "regular_coeff", "regular_type"),  
("dgc_momentum", "param", "grad", "velocity", "learning_rate", "master_param", "current_step_tensor", "nranks_tensor", "mu", "use_nesterov", "regularization_method", "regularization_coeff", "multi_precision", "rescale_grad", "rampup_begin_step"),  
("diag", "x", "offset", "padding_value"),  
("diag_embed", "input", "offset", "dim1", "dim2"),  
("diagonal", "x", "offset", "axis1", "axis2"),  
("digamma", "x"),  
("dirichlet", "alpha"),  
("disable_check_model_nan_inf", "x", "flag"),  
("dist", "x", "y", "p"),  
("dot", "x", "y"),  
("dropout", "x", "seed_tensor", "p", "is_test", "mode", "seed", "fix_seed"),  
("edit_distance", "hyps", "refs", "hypslength", "refslength", "normalized"),  
("eig", "x"),  
("eigh", "x", "UPLO"),  
("eigvals", "x"),  
("eigvalsh", "x", "uplo", "is_test"),  
("elu", "x", "alpha"),  
("empty", "shape", "dtype", "place"),  
("empty_like", "x", "dtype", "place"),  
("enable_check_model_nan_inf", "x", "flag"),  
("equal_all", "x", "y"),  
("erf", "x"),  
("erfinv", "x"),  
("exp", "x"),  
("expand", "x", "shape"),  
("expand_as", "x", "y", "target_shape"),  
("expm1", "x"),  
("exponential_", "x", "lam"),  
("eye", "num_rows", "num_columns", "dtype", "place"),  
("fake_channel_wise_dequantize_max_abs", "x", "scales", "quant_bits", "quant_axis", "x_num_col_dims"),  
("fake_channel_wise_quantize_abs_max", "x", "bit_length", "round_type", "quant_axis", "is_test"),  
("fake_channel_wise_quantize_dequantize_abs_max", "x", "bit_length", "round_type", "quant_axis"),  
("fake_dequantize_max_abs", "x", "scale", "max_range"),  
("fake_quantize_abs_max", "x", "bit_length", "round_type"),  
("fake_quantize_dequantize_abs_max", "x", "bit_length", "round_type"),  
("fake_quantize_dequantize_moving_average_abs_max", "x", "in_scale", "in_accum", "in_state", "moving_rate", "bit_length", "is_test", "round_type"),  
("fake_quantize_moving_average_abs_max", "x", "in_scale", "in_accum", "in_state", "moving_rate", "bit_length", "is_test", "round_type"),  
("fake_quantize_range_abs_max", "x", "in_scale", "iter", "window_size", "bit_length", "is_test", "round_type"),  
("fft_c2c", "x", "axes", "normalization", "forward"),  
("fft_c2r", "x", "axes", "normalization", "forward", "last_dim_size"),  
("fft_r2c", "x", "axes", "normalization", "forward", "onesided"),  
("fill", "x", "value"),  
("fill_diagonal", "x", "value", "offset", "wrap"),  
("fill_diagonal_tensor", "x", "y", "offset", "dim1", "dim2"),  
("flash_attn", "q", "k", "v", "fixed_seed_offset", "attn_mask", "dropout", "causal", "return_softmax", "is_test", "rng_name"),  
("flash_attn_qkvpacked", "qkv", "fixed_seed_offset", "attn_mask", "dropout", "causal", "return_softmax", "is_test", "rng_name"),  
("flash_attn_unpadded", "q", "k", "v", "cu_seqlens_q", "cu_seqlens_k", "fixed_seed_offset", "attn_mask", "max_seqlen_q", "max_seqlen_k", "scale", "dropout", "causal", "return_softmax", "is_test", "rng_name"),  
("flash_attn_varlen_qkvpacked", "qkv", "cu_seqlens_q", "cu_seqlens_k", "fixed_seed_offset", "attn_mask", "max_seqlen_q", "max_seqlen_k", "scale", "dropout", "causal", "return_softmax", "is_test", "rng_name", "varlen_padded"),  
("flash_attn_with_sparse_mask", "q", "k", "v", "attn_mask_start_row_indices", "fixed_seed_offset", "dropout", "causal", "attn_mask_start_row", "return_softmax", "is_test", "rng_name"),  
("flatten", "x", "start_axis", "stop_axis"),  
("flip", "x", "axis"),  
("floor", "x"),  
("fmax", "x", "y"),  
("fmin", "x", "y"),  
("fold", "x", "output_sizes", "kernel_sizes", "strides", "paddings", "dilations"),  
("fractional_max_pool2d", "x", "output_size", "kernel_size", "random_u", "return_mask"),  
("fractional_max_pool3d", "x", "output_size", "kernel_size", "random_u", "return_mask"),  
("frame", "x", "frame_length", "hop_length", "axis"),  
("frobenius_norm", "x", "axis", "keep_dim", "reduce_all"),  
("full", "shape", "value", "dtype", "place"),  
("full_", "output", "shape", "value", "dtype", "place"),  
("full_batch_size_like", "input", "shape", "dtype", "value", "input_dim_idx", "output_dim_idx", "place"),  
("full_int_array", "value", "dtype", "place"),  
("full_like", "x", "value", "dtype", "place"),  
("full_with_tensor", "value", "shape", "dtype"),  
("fused_batch_norm_act", "x", "scale", "bias", "mean", "variance", "momentum", "epsilon", "act_type"),  
("fused_bn_add_activation", "x", "z", "scale", "bias", "mean", "variance", "momentum", "epsilon", "act_type"),  
("fused_multi_transformer", "x", "ln_scales", "ln_biases", "qkv_weights", "qkv_biases", "cache_kvs", "pre_caches", "rotary_tensor", "beam_offset", "time_step", "seq_lengths", "src_mask", "out_linear_weights", "out_linear_biases", "ffn_ln_scales", "ffn_ln_biases", "ffn1_weights", "ffn1_biases", "ffn2_weights", "ffn2_biases", "pre_layer_norm", "epsilon", "residual_alpha", "dropout_rate", "rotary_emb_dims", "is_test", "dropout_implementation", "act_method", "trans_qkvw", "ring_id", "norm_type", "use_neox_rotary_style", "gqa_group_size"),  
("fused_softmax_mask", "x", "mask"),  
("fused_softmax_mask_upper_triangle", "X"),  
("gammaincc", "x", "y"),  
("gammaln", "x"),  
("gather", "x", "index", "axis"),  
("gather_nd", "x", "index"),  
("gather_tree", "ids", "parents"),  
("gaussian", "shape", "mean", "std", "seed", "dtype", "place"),  
("gaussian_inplace", "x", "mean", "std", "seed"),  
("gelu", "x", "approximate"),  
("generate_proposals", "scores", "bbox_deltas", "im_shape", "anchors", "variances", "pre_nms_top_n", "post_nms_top_n", "nms_thresh", "min_size", "eta", "pixel_offset"),  
("graph_khop_sampler", "row", "colptr", "x", "eids", "sample_sizes", "return_eids"),  
("graph_sample_neighbors", "row", "colptr", "x", "eids", "perm_buffer", "sample_size", "return_eids", "flag_perm_buffer"),  
("grid_sample", "x", "grid", "mode", "padding_mode", "align_corners"),  
("group_norm", "x", "scale", "bias", "epsilon", "groups", "data_format"),  
("gru", "input", "h0", "weight", "bias", "activation", "gate_activation", "is_reverse", "origin_mode", "is_test"),  
("gru_unit", "input", "hidden_prev", "weight", "bias", "activation", "gate_activation", "origin_mode"),  
("gumbel_softmax", "x", "temperature", "hard", "axis"),  
("hardshrink", "x", "threshold"),  
("hardsigmoid", "x", "slope", "offset"),  
("hardtanh", "x", "t_min", "t_max"),  
("heaviside", "x", "y"),  
("histogram", "input", "bins", "min", "max"),  
("hsigmoid_loss", "x", "label", "w", "bias", "path", "code", "num_classes", "is_sparse"),  
("huber_loss", "input", "label", "delta"),  
("i0", "x"),  
("i0e", "x"),  
("i1", "x"),  
("i1e", "x"),  
("identity_loss", "x", "reduction"),  
("imag", "x"),  
("increment", "x", "value"),  
("index_add", "x", "index", "add_value", "axis"),  
("index_put", "x", "indices", "value", "accumulate"),  
("index_sample", "x", "index"),  
("index_select", "x", "index", "axis"),  
("index_select_strided", "x", "index", "axis"),  
("instance_norm", "x", "scale", "bias", "epsilon"),  
("inverse", "x"),  
("is_empty", "x"),  
("isclose", "x", "y", "rtol", "atol", "equal_nan"),  
("isfinite", "x"),  
("isinf", "x"),  
("isnan", "x"),  
("kldiv_loss", "x", "label", "reduction", "log_target"),  
("kron", "x", "y"),  
("kthvalue", "x", "k", "axis", "keepdim"),  
("l1_norm", "x"),  
("label_smooth", "label", "prior_dist", "epsilon"),  
("lamb_", "param", "grad", "learning_rate", "moment1", "moment2", "beta1_pow", "beta2_pow", "master_param", "skip_update", "weight_decay", "beta1", "beta2", "epsilon", "always_adapt", "multi_precision"),  
("layer_norm", "x", "scale", "bias", "epsilon", "begin_norm_axis"),  
("leaky_relu", "x", "negative_slope"),  
("lerp", "x", "y", "weight"),  
("lgamma", "x"),  
("limit_by_capacity", "expert_count", "capacity", "n_worker"),  
("linear_interp", "x", "out_size", "size_tensor", "scale_tensor", "data_format", "out_d", "out_h", "out_w", "scale", "interp_method", "align_corners", "align_mode"),  
("linspace", "start", "stop", "number", "dtype", "place"),  
("llm_int8_linear", "x", "weight", "bias", "weight_scale", "threshold"),  
("log", "x"),  
("log10", "x"),  
("log1p", "x"),  
("log2", "x"),  
("log_loss", "input", "label", "epsilon"),  
("log_softmax", "x", "axis"),  
("logcumsumexp", "x", "axis", "flatten", "exclusive", "reverse"),  
("logical_and", "x", "y"),  
("logical_not", "x"),  
("logical_or", "x", "y"),  
("logical_xor", "x", "y"),  
("logit", "x", "eps"),  
("logsigmoid", "x"),  
("logspace", "start", "stop", "num", "base", "dtype", "place"),  
("logsumexp", "x", "axis", "keepdim", "reduce_all"),  
("lstm", "input", "h0", "c0", "weight", "bias", "use_peepholes", "is_reverse", "is_test", "gate_activation", "cell_activation", "candidate_activation"),  
("lstsq", "x", "y", "rcond", "driver"),  
("lu", "x", "pivot"),  
("lu_unpack", "x", "y", "unpack_ludata", "unpack_pivots"),  
("margin_cross_entropy", "logits", "label", "return_softmax", "ring_id", "rank", "nranks", "margin1", "margin2", "margin3", "scale"),  
("masked_multihead_attention_", "x", "cache_kv", "bias", "src_mask", "cum_offsets", "sequence_lengths", "rotary_tensor", "beam_cache_offset", "qkv_out_scale", "out_shift", "out_smooth", "seq_len", "rotary_emb_dims", "use_neox_rotary_style", "compute_dtype", "out_scale", "quant_round_type", "quant_max_bound", "quant_min_bound"),  
("masked_select", "x", "mask"),  
("matrix_nms", "bboxes", "scores", "score_threshold", "nms_top_k", "keep_top_k", "post_threshold", "use_gaussian", "gaussian_sigma", "background_label", "normalized"),  
("matrix_power", "x", "n"),  
("matrix_rank", "x", "tol", "use_default_tol", "hermitian"),  
("matrix_rank_tol", "x", "atol_tensor", "use_default_tol", "hermitian"),  
("max", "x", "axis", "keepdim"),  
("max_pool2d_with_index", "x", "kernel_size", "strides", "paddings", "global_pooling", "adaptive"),  
("max_pool3d_with_index", "x", "kernel_size", "strides", "paddings", "global_pooling", "adaptive"),  
("maxout", "x", "groups", "axis"),  
("mean", "x", "axis", "keepdim"),  
("mean_all", "x"),  
("memcpy_d2h", "x", "dst_place_type"),  
("memcpy_h2d", "x", "dst_place_type"),  
("memory_efficient_attention", "query", "key", "value", "bias", "cu_seqlens_q", "cu_seqlens_k", "causal_diagonal", "seqlen_k", "max_seqlen_q", "max_seqlen_k", "causal", "dropout_p", "scale", "is_test"),  
("merge_selected_rows", "x"),  
("merged_adam_", "param", "grad", "learning_rate", "moment1", "moment2", "beta1_pow", "beta2_pow", "master_param", "beta1", "beta2", "epsilon", "multi_precision", "use_global_beta_pow"),  
("merged_momentum_", "param", "grad", "velocity", "learning_rate", "master_param", "mu", "use_nesterov", "regularization_method", "regularization_coeff", "multi_precision", "rescale_grad"),  
("meshgrid", "inputs"),  
("mish", "x", "lambda"),  
("mode", "x", "axis", "keepdim"),  
("momentum_", "param", "grad", "velocity", "learning_rate", "master_param", "mu", "use_nesterov", "regularization_method", "regularization_coeff", "multi_precision", "rescale_grad"),  
("multi_dot", "x"),  
("multiclass_nms3", "bboxes", "scores", "rois_num", "score_threshold", "nms_top_k", "keep_top_k", "nms_threshold", "normalized", "nms_eta", "background_label"),  
("multinomial", "x", "num_samples", "replacement"),  
("multiplex", "inputs", "index"),  
("mv", "x", "vec"),  
("nadam_", "param", "grad", "learning_rate", "momentum_decay_pow", "beta2_pow", "mu_product", "moment1", "moment2", "master_param", "beta1", "beta2", "epsilon", "momentum_decay", "multi_precision"),  
("nanmedian", "x", "axis", "keepdim", "mode"),  
("nearest_interp", "x", "out_size", "size_tensor", "scale_tensor", "data_format", "out_d", "out_h", "out_w", "scale", "interp_method", "align_corners", "align_mode"),  
("nextafter", "x", "y"),  
("nll_loss", "input", "label", "weight", "ignore_index", "reduction"),  
("nms", "x", "threshold"),  
("nonzero", "condition"),  
("norm", "x", "axis", "epsilon", "is_test"),  
("npu_identity", "x", "format"),  
("numel", "x"),  
("one_hot", "x", "num_classes"),  
("ones", "shape", "dtype", "place"),  
("ones_like", "x", "dtype", "place"),  
("overlap_add", "x", "hop_length", "axis"),  
("p_norm", "x", "porder", "axis", "epsilon", "keepdim", "asvector"),  
("pad", "x", "paddings", "pad_value"),  
("pad3d", "x", "paddings", "mode", "pad_value", "data_format"),  
("partial_concat", "x", "start_index", "length"),  
("partial_sum", "x", "start_index", "length"),  
("pixel_shuffle", "x", "upscale_factor", "data_format"),  
("pixel_unshuffle", "x", "downscale_factor", "data_format"),  
("poisson", "x"),  
("polygamma", "x", "n"),  
("pool2d", "x", "kernel_size", "strides", "paddings", "ceil_mode", "exclusive", "data_format", "pooling_type", "global_pooling", "adaptive", "padding_algorithm"),  
("pool3d", "x", "kernel_size", "strides", "paddings", "ceil_mode", "exclusive", "data_format", "pooling_type", "global_pooling", "adaptive", "padding_algorithm"),  
("pow", "x", "y"),  
("prelu", "x", "alpha", "data_format", "mode"),  
("prior_box", "input", "image", "min_sizes", "max_sizes", "aspect_ratios", "variances", "flip", "clip", "step_w", "step_h", "offset", "min_max_aspect_ratios_order"),  
("prod", "x", "dims", "keep_dim", "reduce_all"),  
("prune_gate_by_capacity", "gate_idx", "expert_count", "n_expert", "n_worker"),  
("psroi_pool", "x", "boxes", "boxes_num", "pooled_height", "pooled_width", "output_channels", "spatial_scale"),  
("put_along_axis", "arr", "indices", "values", "axis", "reduce", "include_self"),  
("pyramid_hash", "x", "w", "white_list", "black_list", "num_emb", "space_len", "pyramid_layer", "rand_len", "drop_out_percent", "is_training", "use_filter", "white_list_len", "black_list_len", "seed", "lr", "distribute_update_vars"),  
("qr", "x", "mode"),  
("radam_", "param", "grad", "learning_rate", "beta1_pow", "beta2_pow", "rho", "moment1", "moment2", "master_param", "beta1", "beta2", "epsilon", "multi_precision"),  
("randint", "low", "high", "shape", "dtype", "place"),  
("random_routing", "prob", "topk_value", "topk_idx"),  
("randperm", "n", "dtype", "place"),  
("rank_attention", "x", "rank_offset", "rank_param", "max_rank", "max_size"),  
("read_file", "filename", "dtype", "place"),  
("real", "x"),  
("reciprocal", "x"),  
("reduce_as", "x", "target"),  
("reindex_graph", "x", "neighbors", "count", "hashtable_value", "hashtable_index"),  
("relu", "x"),  
("relu6", "x"),  
("renorm", "x", "p", "axis", "max_norm"),  
("repeat_interleave", "x", "repeats", "axis"),  
("repeat_interleave_with_tensor_index", "x", "repeats", "axis"),  
("reverse", "x", "axis"),  
("rms_norm", "x", "bias", "residual", "norm_weight", "norm_bias", "epsilon", "begin_norm_axis", "quant_scale", "quant_round_type", "quant_max_bound", "quant_min_bound"),  
("rmsprop_", "param", "mean_square", "grad", "moment", "learning_rate", "mean_grad", "master_param", "epsilon", "decay", "momentum", "centered", "multi_precision"),  
("rnn", "x", "pre_state", "weight_list", "sequence_length", "dropout_state_in", "dropout_prob", "is_bidirec", "input_size", "hidden_size", "num_layers", "mode", "seed", "is_test"),  
("roi_align", "x", "boxes", "boxes_num", "pooled_height", "pooled_width", "spatial_scale", "sampling_ratio", "aligned"),  
("roi_pool", "x", "boxes", "boxes_num", "pooled_height", "pooled_width", "spatial_scale"),  
("roll", "x", "shifts", "axis"),  
("round", "x"),  
("rprop_", "param", "grad", "prev", "learning_rate", "master_param", "learning_rate_range", "etas", "multi_precision"),  
("rrelu", "x", "lower", "upper", "is_test"),  
("rsqrt", "x"),  
("scale", "x", "scale", "bias", "bias_after_scale"),  
("scatter", "x", "index", "updates", "overwrite"),  
("scatter_nd_add", "x", "index", "updates"),  
("searchsorted", "sorted_sequence", "values", "out_int32", "right"),  
("segment_pool", "x", "segment_ids", "pooltype"),  
("selu", "x", "scale", "alpha"),  
("send_u_recv", "x", "src_index", "dst_index", "reduce_op", "out_size"),  
("send_ue_recv", "x", "y", "src_index", "dst_index", "message_op", "reduce_op", "out_size"),  
("send_uv", "x", "y", "src_index", "dst_index", "message_op"),  
("sequence_conv", "x", "padding_data", "filter", "context_length", "padding_trainable", "context_start", "context_stride"),  
("sequence_mask", "x", "max_len", "out_dtype"),  
("set_value_with_tensor", "x", "values", "starts", "ends", "steps", "axes", "decrease_axes", "none_axes"),  
("sgd_", "param", "learning_rate", "grad", "master_param", "multi_precision"),  
("shape", "input"),  
("shard_index", "input", "index_num", "nshards", "shard_id", "ignore_value"),  
("shuffle_batch", "x", "seed", "startup_seed"),  
("shuffle_channel", "x", "group"),  
("sigmoid", "x"),  
("sigmoid_cross_entropy_with_logits", "x", "label", "pos_weight", "normalize", "ignore_index"),  
("sign", "x"),  
("silu", "x"),  
("sin", "x"),  
("sinh", "x"),  
("slice", "input", "axes", "starts", "ends", "infer_flags", "decrease_axis"),  
("slogdet", "x"),  
("softplus", "x", "beta", "threshold"),  
("softshrink", "x", "threshold"),  
("softsign", "x"),  
("solve", "x", "y"),  
("sparse_attention", "q", "k", "v", "offset", "columns", "key_padding_mask", "attn_mask"),  
("spectral_norm", "weight", "u", "v", "dim", "power_iters", "eps"),  
("split", "x", "sections", "axis"),  
("split_with_num", "x", "num", "axis"),  
("sqrt", "x"),  
("square", "x"),  
("squared_l2_norm", "x"),  
("squeeze", "x", "axis"),  
("stack", "x", "axis"),  
("standard_gamma", "x"),  
("stanh", "x", "scale_a", "scale_b"),  
("stft", "x", "window", "n_fft", "hop_length", "normalized", "onesided"),  
("strided_slice", "x", "axes", "starts", "ends", "strides"),  
("sum", "x", "axis", "dtype", "keepdim"),
("svd", "x", "full_matrices"),  
("swiglu", "x", "y"),  
("swish", "x"),  
("sync_batch_norm_", "x", "mean", "variance", "scale", "bias", "is_test", "momentum", "epsilon", "data_format", "use_global_stats", "trainable_statistics"),  
("take_along_axis", "arr", "indices", "axis"),  
("tan", "x"),  
("tanh", "x"),  
("tanh_shrink", "x"),  
("tdm_child", "x", "tree_info", "child_nums", "dtype"),  
("tdm_sampler", "x", "travel", "layer", "output_positive", "neg_samples_num_list", "layer_offset_lod", "seed", "dtype"),  
("temporal_shift", "x", "seg_num", "shift_ratio", "data_format"),  
("tensor_unfold", "input", "axis", "size", "step"),  
("thresholded_relu", "x", "threshold"),  
("top_p_sampling", "x", "ps", "threshold", "seed"),  
("topk", "x", "k", "axis", "largest", "sorted"),  
("trace", "x", "offset", "axis1", "axis2"),  
("trans_layout", "x", "perm"),  
("transpose", "x", "perm"),  
("triangular_solve", "x", "y", "upper", "transpose", "unitriangular"),  
("tril", "x", "diagonal"),  
("tril_indices", "rows", "cols", "offset", "dtype", "place"),  
("trilinear_interp", "x", "out_size", "size_tensor", "scale_tensor", "data_format", "out_d", "out_h", "out_w", "scale", "interp_method", "align_corners", "align_mode"),  
("triu", "x", "diagonal"),  
("triu_indices", "row", "col", "offset", "dtype", "place"),  
("trunc", "input"),  
("truncated_gaussian_random", "shape", "mean", "std", "seed", "a", "b", "dtype", "place"),  
("unbind", "input", "axis"),  
("unfold", "x", "kernel_sizes", "strides", "paddings", "dilations"),  
("uniform", "shape", "dtype", "min", "max", "seed", "place"),  
("uniform_inplace", "x", "min", "max", "seed", "diag_num", "diag_step", "diag_val"),  
("uniform_random_batch_size_like", "input", "shape", "input_dim_idx", "output_dim_idx", "min", "max", "seed", "diag_num", "diag_step", "diag_val", "dtype"),  
("unique_consecutive", "x", "return_inverse", "return_counts", "axis", "dtype"),  
("unpool", "x", "indices", "ksize", "strides", "padding", "output_size", "data_format"),  
("unpool3d", "x", "indices", "ksize", "strides", "paddings", "output_size", "data_format"),  
("unsqueeze", "x", "axis"),  
("unstack", "x", "axis", "num"),  
("update_loss_scaling_", "x", "found_infinite", "prev_loss_scaling", "in_good_steps", "in_bad_steps", "incr_every_n_steps", "decr_every_n_nan_or_inf", "incr_ratio", "decr_ratio", "stop_update"),  
("view_dtype", "input", "dtype"),  
("view_shape", "input", "dims"),  
("viterbi_decode", "potentials", "transition_params", "lengths", "include_bos_eos_tag"),  
("warpctc", "logits", "label", "logits_length", "labels_length", "blank", "norm_by_times"),  
("warprnnt", "input", "label", "input_lengths", "label_lengths", "blank", "fastemit_lambda"),  
("weight_dequantize", "x", "scale", "algo", "out_dtype", "group_size"),  
("weight_only_linear", "x", "weight", "bias", "weight_scale", "weight_dtype", "arch", "group_size"),  
("weight_quantize", "x", "algo", "arch", "group_size"),  
("weighted_sample_neighbors", "row", "colptr", "edge_weight", "input_nodes", "eids", "sample_size", "return_eids"),  
("where", "condition", "x", "y"),  
("yolo_box", "x", "img_size", "anchors", "class_num", "conf_thresh", "downsample_ratio", "clip_bbox", "scale_x_y", "iou_aware", "iou_aware_factor"),  
("yolo_box_head", "x", "anchors", "class_num"),  
("yolo_box_post", "boxes0", "boxes1", "boxes2", "image_shape", "image_scale", "anchors0", "anchors1", "anchors2", "class_num", "conf_thresh", "downsample_ratio0", "downsample_ratio1", "downsample_ratio2", "clip_bbox", "scale_x_y", "nms_threshold"),  
("yolo_loss", "x", "gt_box", "gt_label", "gt_score", "anchors", "anchor_mask", "class_num", "ignore_thresh", "downsample_ratio", "use_label_smooth", "scale_x_y"),  
("zeros", "shape", "dtype", "place"),  
("zeros_like", "x", "dtype", "place"),  
("chunk_eval", "inference", "label", "seq_length", "num_chunk_types", "chunk_scheme", "excluded_chunk_types"),  
("moe", "x", "gate", "bmm0", "bias0", "bmm1", "bias1", "act_type"),  
("number_count", "numbers", "upper_range"),  
]

phi_ops_yaml_legacy_static_ops = [
("add", "x", "y"),  
("add_n", "inputs"),  
("all_reduce", "x", "ring_id", "reduce_type"),  
("assign", "x"),  
("assign_value", "shape", "dtype", "values", "place"),  
("barrier", "x", "ring_id"),  
("batch_fc", "input", "w", "bias"),  
("batch_norm", "x", "mean", "variance", "scale", "bias", "is_test", "momentum", "epsilon", "data_format", "use_global_stats", "trainable_statistics"),  
("c_allreduce_avg", "x", "ring_id", "use_calc_stream", "use_model_parallel"),  
("c_embedding", "weight", "x", "start_index", "vocab_size"),  
("c_reduce_avg", "x", "ring_id", "root_id", "use_calc_stream"),  
("c_reduce_max", "x", "ring_id", "root_id", "use_calc_stream"),  
("c_reduce_min", "x", "ring_id", "root_id", "use_calc_stream"),  
("c_reduce_prod", "x", "ring_id", "root_id", "use_calc_stream"),  
("c_reducescatter", "x", "ring_id", "nranks", "use_calc_stream"),  
("c_scatter", "x", "ring_id", "root", "nranks", "use_calc_stream"),  
("c_split", "x", "rank", "nranks", "ring_id", "use_calc_stream", "use_model_parallel"),  
("coalesce_tensor_", "input", "dtype", "copy_data", "set_constant", "persist_output", "constant", "use_align", "align_size", "size_of_dtype", "concated_shapes", "concated_ranks"),  
("dequantize_linear", "x", "scale", "zero_point", "in_accum", "in_state", "quant_axis", "bit_length", "round_type", "is_test", "only_observer"),  
("distribute_fpn_proposals", "fpn_rois", "rois_num", "min_level", "max_level", "refer_level", "refer_scale", "pixel_offset"),  
("distributed_fused_lamb", "param", "grad", "fp32_fused_param", "fp32_fused_grad", "fp16_fused_param", "fp16_fused_grad", "moment1", "moment2", "beta1pow", "beta2pow", "fused_param_offsets", "fp32_shard_fused_param_offsets", "fp16_shard_fused_param_offsets", "param_info", "param_order", "learning_rate", "global_scale", "beta1", "beta2", "epsilon", "max_global_grad_norm", "weight_decay", "clip_after_allreduce", "acc_steps", "use_master_param_norm", "use_master_acc_grad", "is_grad_scaled_by_nranks", "nranks", "use_hierarchical_allreduce", "ring_ids"),  
("distributed_lookup_table", "ids", "w", "table_id", "is_distributed", "lookup_table_version", "padding_idx", "dtype", "is_test"),  
("distributed_push_sparse", "ids", "shows", "clicks", "table_id", "size", "is_distributed", "push_sparse_version", "padding_idx", "dtype", "is_test", "use_cvm_op"),  
("divide", "x", "y"),  
("einsum", "x", "equation"),  
("elementwise_pow", "x", "y"),  
("embedding", "x", "weight", "padding_idx", "sparse"),  
("equal", "x", "y"),  
("feed", "name", "col"), 
("fetch", "x", "name", "col"),  
("floor_divide", "x", "y"),  
("fused_adam_", "params", "grads", "learning_rate", "moments1", "moments2", "beta1_pows", "beta2_pows", "master_params", "skip_update", "beta1", "beta2", "epsilon", "chunk_size", "weight_decay", "use_adamw", "multi_precision", "use_global_beta_pow"),  
("get_tensor_from_selected_rows", "x"),  
("global_gather", "x", "local_count", "global_count", "ring_id", "use_calc_stream"),  
("global_scatter", "x", "local_count", "global_count", "ring_id", "use_calc_stream"),  
("greater_equal", "x", "y"),  
("greater_than", "x", "y"),  
("hardswish", "x"),  
("less_equal", "x", "y"),  
("less_than", "x", "y"),  
("load_combine", "file_path", "load_as_fp16", "model_from_memory"),  
("lod_array_length", "x"),  
("lrn", "x", "n", "k", "alpha", "beta", "data_format"),  
("matmul", "x", "y", "transpose_x", "transpose_y"),  
("matmul_with_flatten", "x", "y", "x_num_col_dims", "y_num_col_dims"),  
("maximum", "x", "y"),  
("memcpy", "x", "dst_place_type"),  
("min", "x", "axis", "keepdim"),  
("minimum", "x", "y"),  
("multiply", "x", "y"),  
("nop", "x"),  
("not_equal", "x", "y"),  
("partial_allgather", "x", "nranks", "rank", "ring_id", "use_calc_stream"),  
("partial_recv", "ring_id", "peer", "dtype", "out_shape", "use_calc_stream", "num", "id"),  
("print", "in", "first_n", "message", "summarize", "print_tensor_name", "print_tensor_type", "print_tensor_shape", "print_tensor_layout", "print_tensor_lod", "print_phase", "is_forward"),  
("pull_box_sparse", "w", "ids", "is_sparse", "is_distributed", "size"),  
("pull_gpups_sparse", "w", "ids", "size", "is_sparse", "is_distributed"),  
("pull_sparse_v2", "ids", "w", "embedding_dim", "table_id", "accessor_class", "ctr_label_name", "padding_id", "scale_sparse_grad", "input_names", "is_distributed"),  
("push_dense", "ids", "table_id", "scale_data_norm", "input_names"),  
("push_sparse_v2", "ids", "w", "out_grad_in", "embedding_dim", "table_id", "accessor_class", "ctr_label_name", "padding_id", "scale_sparse_grad", "input_names", "is_distributed"),  
("quantize_linear", "x", "scale", "zero_point", "in_accum", "in_state", "quant_axis", "bit_length", "round_type", "is_test", "only_observer"),  
("recv_v2", "out_shape", "dtype", "peer", "ring_id", "use_calc_stream", "dynamic_shape"),  
("remainder", "x", "y"),  
("reshape", "x", "shape"),  
("row_conv", "x", "filter"),  
("save_combine", "x", "file_path", "overwrite", "save_as_fp16", "save_to_memory"),  
("seed", "seed", "deterministic", "rng_name", "force_cpu"),  
("send_and_recv", "x", "message_name", "send_var_name", "recv_var_name", "trainer_id", "mode", "endpoints", "next_endpoints", "previous_endpoints"),  
("send_v2", "x", "ring_id", "peer", "use_calc_stream", "dynamic_shape"),  
("set_value", "x", "starts", "ends", "steps", "axes", "decrease_axes", "none_axes", "shape", "values"),  
("shadow_feed", "x"),  
("shadow_feed_tensors", "x"),  
("share_data_", "x"),  
("soft_relu", "x", "threshold"),  
("softmax", "x", "axis"),  
("subtract", "x", "y"),  
("tile", "x", "repeat_times"),  
("unique", "x", "return_index", "return_inverse", "return_counts", "axis", "dtype", "is_sorted"),  
("write_to_array", "i", "x"),  
("c_softmax_with_cross_entropy", "logits", "label", "ignore_index", "ring_id", "rank", "nranks"),  
("dpsgd", "param", "grad", "learning_rate", "clip", "batch_size", "sigma", "seed"),  
("ftrl", "param", "squared_accumulator", "linear_accumulator", "grad", "learning_rate", "l1", "l2", "lr_power"),  
("fused_attention", "x", "ln_scale", "ln_bias", "qkv_weight", "qkv_bias", "cache_kv", "src_mask", "out_linear_weight", "out_linear_bias", "ln_scale_2", "ln_bias_2", "num_heads", "transpose_qkv_wb", "pre_layer_norm", "epsilon", "attn_dropout_rate", "is_test", "attn_dropout_fix_seed", "attn_dropout_seed", "attn_dropout_implementation", "dropout_rate", "dropout_fix_seed", "dropout_seed", "dropout_implementation", "ln_epsilon", "add_residual", "ring_id"),  
("fused_feedforward", "x", "dropout1_seed", "dropout2_seed", "linear1_weight", "linear1_bias", "linear2_weight", "linear2_bias", "ln1_scale", "ln1_bias", "ln2_scale", "ln2_bias", "pre_layer_norm", "ln1_epsilon", "ln2_epsilon", "act_method", "dropout1_prob", "dropout2_prob", "dropout1_implementation", "dropout2_implementation", "is_test", "dropout1_fix_seed", "dropout2_fix_seed", "dropout1_seed_val", "dropout2_seed_val", "add_residual", "ring_id"),  
("lars_momentum", "param", "grad", "velocity", "learning_rate", "master_param", "mu", "lars_coeff", "lars_weight_decay", "epsilon", "multi_precision", "rescale_grad"),  
("match_matrix_tensor", "x", "y", "w", "dim_t"),  
("moving_average_abs_max_scale", "x", "in_accum", "in_state", "moving_rate", "is_test"),  
("nce", "input", "label", "weight", "bias", "sample_weight", "custom_dist_probs", "custom_dist_alias", "custom_dist_alias_probs", "num_total_classes", "custom_neg_classes", "num_neg_samples", "sampler", "seed", "is_sparse", "remote_prefetch", "is_test"),  
("onednn_to_paddle_layout", "x", "dst_layout"),  
("partial_send", "x", "ring_id", "peer", "use_calc_stream", "num", "id"),  
("sparse_momentum", "param", "grad", "velocity", "index", "learning_rate", "master_param", "mu", "axis", "use_nesterov", "regularization_method", "regularization_coeff", "multi_precision", "rescale_grad"),  
]

op_name_x_arg_names = phi_ops_yaml_ops + phi_ops_yaml_legacy_static_ops
