from collections import namedtuple

BoolAttribute = namedtuple("BoolAttribute", ["value"])
Complex64Attribute = namedtuple("Complex64Attribute", ["real", "imag"])
Complex128Attribute = namedtuple("Complex128Attribute", ["real", "imag"])
Float32Attribute = namedtuple("Float32Attribute", ["value"])
Float64Attribute = namedtuple("Float64Attribute", ["value"])
Int32Attribute = namedtuple("Int32Attribute", ["value"])
IndexAttribute = namedtuple("IndexAttribute", ["value"])
Int64Attribute = namedtuple("Int64Attribute", ["value"])
PointerAttribute = namedtuple("PointerAttribute", ["value"])
TypeAttribute = namedtuple("TypeAttribute", ["value"])
StrAttribute = namedtuple("StrAttribute", ["value"])
ArrayAttribute = namedtuple("ArrayAttribute", ["value"])
TensorNameAttribute = namedtuple("TensorNameAttribute", ["value"])
IntArrayAttribute = namedtuple("IntArrayAttribute", ["value"])
ScalarAttribute = namedtuple("ScalarAttribute", ["value"])
DataTypeAttribute = namedtuple("DataTypeAttribute", ["value"])
PlaceAttribute = namedtuple("PlaceAttribute", ["type", "device"])
DataLayoutAttribute = namedtuple("DataLayoutAttribute", ["value"])
KernelAttribute = namedtuple("KernelAttribute", ["value"])
GroupInfoAttribute = namedtuple("GroupInfoAttribute", ["value"])
CINNKernelInfoAttribute = namedtuple("CINNKernelInfoAttribute", ["value"])
SymbolAttribute = namedtuple("SymbolAttribute", ["value"])
UnclassifiedAttribute = namedtuple("UnclassifiedAttribute", ["value"])

